.gitmodules, README.md
This PR changes the submodule configuration for the `json` submodule from using SSH to https. This should allow people with no valid SSH key setup to properly clone the repository.
Furthermore it adds a note stating that the pre-built wheels are not yet published and how to work with the package in the meantime.
Resolves #1
=> 🔧  Change submodule config and 📝 add note about wheels

include/Utils.hpp
This PR fixes a compilation error that recently popped up with the addition of gcc 12 to Ubuntu 22.04 GitHub runners.
The main reason for the failure is that the C++ standard does not mandate that `std::swap` works on `std::vector<bool>` since bit vectors are "special". See https://stackoverflow.com/questions/58660207/why-doesnt-stdswap-work-on-vectorbool-elements-under-clang-win for some more context.
=> 🐛 Fix compilation error under gcc-12

README.md
=> fix zenodo link in readme

.github/workflows/deploy.yml
=> 🔧 Fix upload action case style

.gitmodules, .pre-commit-config.yaml, CMakeLists.txt, MANIFEST.in, mqt/qecc/CMakeLists.txt, mqt/qecc/bindings.cpp, mqt/qecc/cc_decoder/color_code.py, mqt/qecc/cc_decoder/decoder.py, mqt/qecc/pyqecc.pyi, scripts/numerics/code_construct/lifted_hgp.py, setup.py, src/CMakeLists.txt
This PR replaces the QFR submodule with the newly introduced MQT Core library that subsumes the QFR, DD package, and ZX package. At the moment, this entails no functional changes and only required minor adaptions.
=> 🚚 Move to MQT Core package

noxfile.py, pyproject.toml
This small PR updates the pytest script runner test dependency lower cap.
This also removes the (now superfluous) upper cap on `qiskit-terra` that has been put in place until the release of `qiskit_aer==0.12.1`.
=> ⬆️  Update Script Runner Test Dependency

noxfile.py, pyproject.toml, test/python/constraints.txt
This PR updates the minimum `pybind11` version to 2.12, which was released a couple weeks ago and brings several big improvements, including compatibility with Numpy 2.0 which will be released soon, see https://github.com/cda-tum/mqt-qcec/pull/383
=> update pybind version

.github/workflows/ci.yml, .github/workflows/deploy.yml, .github/workflows/python-ci.yml
GitHub's latest rollout of macOS-14 (which uses Apple Silicon hardware) as macOS-latest has broken the CI pipelines here.
This PR fixes the workflows and updates the configuration a little bit.
This should become much easier once this repository no longer depends on the flint package because then the reusable MQT workflows can be used.
=> 👷🏼 fix and update CI

pyproject.toml
New numpy version break binary compatibility with Cython. For now we restrict numpy version until this issue is fixed.
=> Restrict numpy to version < 2.

.github/workflows/reusable-code-ql.yml
This small PR adjusts the CodeQL config to ignore the `build` folder. Since the introduction of using `FetchContent`, the build folder also contains a `_deps` subfolder with all the fetched dependencies. These might (and in the case of QECC here, will) trigger CodeQL warnings we have no control over.
This PR should reduce the number of warnings flagged for the project.
=> 🔧👷 properly exclude `build` directory from CodeQL

include/ecc/Ecc.hpp, include/ecc/Id.hpp, include/ecc/Q18Surface.hpp, include/ecc/Q3Shor.hpp, include/ecc/Q5Laflamme.hpp, include/ecc/Q7Steane.hpp, include/ecc/Q9Shor.hpp, include/ecc/Q9Surface.hpp, src/CMakeLists.txt, src/ecc/CMakeLists.txt, src/ecc/Ecc.cpp, src/ecc/Q18Surface.cpp, src/ecc/Q3Shor.cpp, src/ecc/Q5Laflamme.cpp, src/ecc/Q7Steane.cpp, src/ecc/Q9Shor.cpp, src/ecc/Q9Surface.cpp, src/python/CMakeLists.txt, src/python/bindings.cpp, test/CMakeLists.txt, test/test_ecc_functionality.cpp
This PR moves the ECC (framework) related code from MQT Core to this repository.
It is hard to maintain in MQT Core and feels like an alien there.
Much better suited in this library.
A corresponding PR in MQT Core will remove the respective functionality there.
=> 🚚 transfer the ECC framework code from MQT Core

test/python/ft_stateprep/test_stateprep.py
Overlooked a test in the last PR. Opening a new PR.
=> Remove resource-intensive tests

src/mqt/qecc/ft_stateprep/state_prep.py, test/python/ft_stateprep/test_stateprep.py
This PR fixes some issues with certain codes. 
There was a bug when the code was defined over a number of qubits, which is an exact power of 2, leading to the optimal state prep circuit failing to be synthesized.
Another issue occurred when looking at d=2 codes, which cannot be used for error correction but only for error detection. I have added functionality to set whether one wants to create the circuit for error detection or error correction in the `StatePrepCircuit` class.
Fixes #265
=> Fix small code bugs for FT Stateprep

src/mqt/qecc/ft_stateprep/state_prep.py
Due to a missing check in the propagation of errors, some Z-errors were propagated incorrectly
=> Fix incorrect placement of z-errors

.github/workflows/reusable-python-packaging.yml, noxfile.py, pyproject.toml
This PR updates the ldpc dependency to its latest version, which brings compatibility with numpy 2.0 and ships Python 3.12 (as well as 3.13) wheels.
In addition, the new version contains a fix for the invalid escape sequence that was triggering test errors and had to be excluded.
This allows to remove quite some workarounds and streamlines the installation process of QECC.
Fixes #264
=> ⬆️ update ldpc with numpy 2 and Python 3.12+ support

src/mqt/qecc/ft_stateprep/state_prep.py
There is an error in the computation of fault sets in state preparation circuits. Sometimes, the gates are not traversed in the correct topological order, and thus, some faults are not correct. This didn't show up before because the faults were still caught by the verification circuits. 
Fixes # (issue)
=> Fix error propagation.

pyproject.toml
This PR temporarily pins the ldpc package to `<2` as the new version has broken QECC.
This is just meant as a quick fix until we ensured compatibility with `v2`
=> 📌 temporary `ldpc<2`

docs/StatePrep.ipynb
Because we moved the files in the det. PR links in the documentation were no longer valid.
=> 📝 Fixed wrong links in documentation

docs/StatePrep.ipynb
Fixed type regarding the number of CNOT gates for the steane code
=> Fixed documentation typo regarding the number of CNOT gates for the steane code

src/mqt/qecc/circuit_synthesis/simulation_det.py
This PR fixes a minor problem in the simulation of deterministic state preparation circuits. qsample protocols need to be flagged whether they are fault-tolerant or not at construction to ensure that bounds are correctly computed. This PR sets this flag.
=> Set the `fault_tolerant` flag in the qsample protocol.

.readthedocs.yaml
This PR disables the PDF build on RtD because it keeps failing us. It is a copy of https://github.com/munich-quantum-toolkit/core/pull/1023.
=> 📝🩹 Disable PDF build on RtD

test/python/circuit_synthesis/test_cat_states.py, test/python/circuit_synthesis/test_encoder_synthesis.py, test/python/circuit_synthesis/test_stateprep.py
For some reason, lately, the Z3 solver is slower on macOS 13. This PR disables running test cases with harder instances for the Z3 solver on macOS.
=> Fix flaky test fails due to timeouts on macos.

src/mqt/qecc/circuit_synthesis/state_prep.py
The `max_ancillas` parameter was ignored in the verification circuit synthesis. This probably also fixes the flaky tests since the verification circuit synthesis previously built the SAT formula using the most ancillas.
=> Set maximum ancillas correctly in verification circuit synthesis.
